Write performance benchmark for reading from a big CSV file
codeincorp/mongo pull request #30
Opened 2024-05-11 01:01 UTC by MaxJuneKim

Fixes codeincorp/mongo#18

2024-05-11 06:57 UTC, yun-soo reviewed
Almost LGTM. Left a few minor comments.

2024-05-11 06:57 UTC, yun-soo commented on src/mongo/db/storage/csv_bm.cpp
> +    mongo::CsvFileInput input(csvFile, metadataFile);
[nit] We don't need use `mongo::`

2024-05-11 06:57 UTC, yun-soo commented on src/mongo/db/storage/csv_bm.cpp
> +    input.open();
[nit] Why not doing this inside `readCsv()`

2024-05-11 06:57 UTC, yun-soo commented on src/mongo/db/storage/mv_bm_csv.sh
> +#!/bin/sh
Good job!
Can we add license header here?

2024-05-11 06:57 UTC, yun-soo commented on src/mongo/db/storage/mv_bm_csv.sh
> +    tar -xzvf /tmp/customers-2000000.zip -C /tmp/
Should we remove the header line? Same comment on people & organizations

2024-05-11 06:57 UTC, yun-soo commented on src/mongo/db/storage/csv_bm.cpp
> +    std::cout << builder.done().toString() << std::endl;
Can we print this prettier?

2024-05-12 03:55 UTC, codein-dev reviewed
Almost LGTM. Left a few minor comments!

2024-05-12 03:55 UTC, codein-dev commented on src/mongo/db/storage/csv_bm.cpp
> +    mongo::CsvFileInput input(csvFile, metadataFile);
[nit] We don't need use `mongo::`

2024-05-12 03:55 UTC, codein-dev commented on src/mongo/db/storage/csv_bm.cpp
> +    input.open();
[nit] Why not doing this inside `readCsv()`

2024-05-12 03:55 UTC, codein-dev commented on src/mongo/db/storage/csv_bm.cpp
> +    std::cout << builder.done().toString() << std::endl;
Can we print this prettier?

2024-05-12 03:55 UTC, codein-dev commented on src/mongo/db/storage/mv_bm_csv.sh
> +#!/bin/sh
Good job!
Can we add license header here?

2024-05-12 03:55 UTC, codein-dev commented on src/mongo/db/storage/mv_bm_csv.sh
> +    tar -xzvf /tmp/customers-2000000.zip -C /tmp/
Should we remove the header line? Same comment on people & organizations

2024-05-12 03:55 UTC, codein-dev commented on src/mongo/db/storage/csv_bm.cpp
> +
Could you add description of what this test does?

2024-05-12 22:25 UTC, codein-dev commented on src/mongo/db/storage/mv_bm_csv.sh
> +    tar -xzvf /tmp/people-2000000.zip -C /tmp/
I think we should use unzip instead.

2024-05-12 22:26 UTC, codein-dev requested changes
I think we should unzip instead of tar.

2024-05-12 22:40 UTC, codein-dev commented on src/mongo/db/storage/mv_bm_csv.sh
> +    echo 'Index/int32,Organization Id/string,Name/string,Website/string,Country/string,Description/string,Founded/string,Industry/string,Number of employees/int32' > /tmp/organizations.txt
I see following error counts for organizations.

```
{ csv: { incompleteConversionToNumeric: 1332581, invalidInt32: 667421, invalidInt64: 0, invalidDouble: 0, outOfRange: 0, invalidDate: 0, invalidOid: 0, invalidBoolean: 0, metadataAndDataDifferentLength: 667419, totalErrorCount: 2667421 } }
```

Would the metadata be probably wrong?

2024-05-16 23:47 UTC, MaxJuneKim reviewed
Addressed the comments and added the new fields to CsvFileIoStats

2024-05-16 23:47 UTC, MaxJuneKim commented on src/mongo/db/storage/mv_bm_csv.sh
> +    tar -xzvf /tmp/people-2000000.zip -C /tmp/
Is unzip faster? For some reason, unzip does not work on my Mac and other solutions that I explored only offer to use p7zip instead?

2024-05-16 23:47 UTC, MaxJuneKim commented on src/mongo/db/storage/mv_bm_csv.sh
> +    tar -xzvf /tmp/people-2000000.zip -C /tmp/
Done (using 7zip)

2024-05-16 23:47 UTC, MaxJuneKim commented on src/mongo/db/storage/mv_bm_csv.sh
> +    tar -xzvf /tmp/customers-2000000.zip -C /tmp/
Done

2024-05-16 23:47 UTC, MaxJuneKim commented on src/mongo/db/storage/csv_bm.cpp
> +    std::cout << builder.done().toString() << std::endl;
eg:
field1: ...
field2: ...
field3: ...

2024-05-16 23:47 UTC, MaxJuneKim commented on src/mongo/db/storage/csv_bm.cpp
> +    mongo::CsvFileInput input(csvFile, metadataFile);
Done

2024-05-16 23:47 UTC, MaxJuneKim commented on src/mongo/db/storage/csv_bm.cpp
> +    input.open();
Done

2024-05-16 23:47 UTC, MaxJuneKim commented on src/mongo/db/storage/csv_bm.cpp
> +
Done

2024-05-16 23:47 UTC, MaxJuneKim commented on src/mongo/db/storage/mv_bm_csv.sh
> +    echo 'Index/int32,Organization Id/string,Name/string,Website/string,Country/string,Description/string,Founded/string,Industry/string,Number of employees/int32' > /tmp/organizations.txt
It is not
It stems from the fact that the organizations-2000000.csv file contains 1,332,581 lines that whose final field is int32, and they all seem to have a hidden special character after that, probably because they are the end of the line, resulting in exactly 1,332,581 incompleteConversionToNumericError

2024-05-16 23:47 UTC, MaxJuneKim commented on src/mongo/db/storage/mv_bm_csv.sh
> +#!/bin/sh
Done

2024-05-16 23:47 UTC, MaxJuneKim commented on src/mongo/db/storage/csv_bm.cpp
> +    std::cout << builder.done().toString() << std::endl;
Done.

2024-05-17 00:42 UTC, codein-dev approved these changes
Good job! LGTM. Left a few minor comments but those are not blockers.

2024-05-17 00:42 UTC, codein-dev commented on src/mongo/db/storage/csv_bm.cpp
> + * This benchmark measures the performance of CsvFileInput when it is readinf from a big csv file.
```suggestion
 * This benchmark measures the performance of CsvFileInput when it reads a big csv file.
```

2024-05-17 00:42 UTC, codein-dev commented on src/mongo/db/storage/csv_bm.cpp
> +          << std::to_string(csvIoStats->_incompleteConversionToNumeric) << '\n';
[nit] We don't need to use `to_string()` here.

2024-05-17 00:42 UTC, codein-dev commented on src/mongo/db/storage/csv_file.cpp
> +    _ioStats->_bsonsReturned++;
[nit] I think it'd be better to do this in doRead().

2024-05-17 00:42 UTC, codein-dev commented on src/mongo/db/storage/csv_bm.cpp
> +    state.counters["File_Size"] = fileSize;
Good job!

2024-05-17 00:42 UTC, codein-dev commented on src/mongo/db/storage/csv_bm.cpp
> +    state.counters["BSON_Size"] = totalBytes;
Let's add input size as well.

2024-05-17 20:30 UTC, MaxJuneKim commented on src/mongo/db/storage/csv_bm.cpp
> +    state.counters["BSON_Size"] = totalBytes;
Done

2024-05-17 20:30 UTC, MaxJuneKim commented on src/mongo/db/storage/csv_bm.cpp
> +    state.counters["File_Size"] = fileSize;
Done

2024-05-17 20:30 UTC, MaxJuneKim commented on src/mongo/db/storage/csv_bm.cpp
> + * This benchmark measures the performance of CsvFileInput when it is readinf from a big csv file.
Done

2024-05-17 20:30 UTC, MaxJuneKim commented on src/mongo/db/storage/csv_bm.cpp
> +          << std::to_string(csvIoStats->_incompleteConversionToNumeric) << '\n';
Done

2024-05-17 20:31 UTC, MaxJuneKim commented on src/mongo/db/storage/csv_file.cpp
> +    _ioStats->_bsonsReturned++;
Done

2024-05-17 20:37 UTC, merged